In [5]:
ages = [12,85,46,54,12000,32]
for age in ages:
    if len(str(age))>2:
        pass
    else:
        print(age)

12
85
46
54
32

In [6]:
for age in ages:
    if age>100:
        pass
    else:
        print(age)

12
85
46
54
32

In [10]:
names = ["kamau", "njau", "kennedy", "john" , "mumbi"]

for name in names:
    
    if name == "kamau":
        print("kamau ni nugu")
    else:
        print("hallo {}".format(name))

kamau ni nugu
hallo njau
hallo kennedy
hallo john
hallo mumbi

In [13]:
import random

numbers = [random.random()*100 for i in range(100)]

In [14]:
numbers

[66.58282082416545,
 66.00588840062953,
 34.027483110403324,
 51.01550746057673,
 21.124174819602825,
 35.66778994692885,
 68.77780676387907,
 81.91582854152043,
 36.0978327775854,
 27.403901233701333,
 30.778837475528963,
 56.65740067591002,
 45.062684766134694,
 78.11429441743762,
 16.55607109057312,
 50.209130406236056,
 75.48189469349387,
 78.23993707423985,
 33.71558337942935,
 85.08865768082377,
 78.59859045042353,
 57.48563194328806,
 64.88137300894287,
 47.56509707415519,
 63.1246540446456,
 11.428421685889113,
 95.57273537813863,
 88.75887352937245,
 81.88995199961575,
 20.001419243052432,
 96.97265927372273,
 43.06914141005015,
 46.22707923216735,
 98.16820622083783,
 91.97278818020618,
 94.68157567503343,
 78.76088320117127,
 27.11991217588,
 43.038209138705994,
 55.607705165976476,
 87.31926576186238,
 54.67348884215303,
 81.5808542255201,
 35.235261445876716,
 98.84890846712321,
 54.52627694217623,
 99.58377919830303,
 62.7482520976428,
 88.70461180043718,
 20.439799738768162,
 39.7794901613036,
 27.81635997854186,
 67.8914538085759,
 83.70438861510428,
 48.145423835490284,
 83.74855364367978,
 94.28826597922222,
 41.232197382720216,
 8.723859456825188,
 2.741047652534212,
 51.0458399442371,
 63.64150273816359,
 57.11585772491738,
 37.16434452493247,
 39.24605815199155,
 19.04333204874239,
 12.712390736202629,
 33.97511521004556,
 60.8808857662489,
 8.549451497479676,
 17.20780093152985,
 50.4847173389815,
 11.387912976842463,
 4.384999484243357,
 26.32783416226999,
 9.910896896177324,
 99.01392811328972,
 94.32279325345503,
 38.577289522173274,
 57.69942640981286,
 37.8042987185223,
 64.12914899242061,
 29.697203749742584,
 9.262188001394877,
 84.11279548607091,
 48.43592369752611,
 72.09053042133952,
 95.11919872187168,
 86.10124991805922,
 55.36249708525764,
 56.26985454096738,
 7.868031746616455,
 27.629134124968946,
 33.59318442550104,
 82.03223204772816,
 75.0938423870013,
 90.91609430821042,
 49.21285597497739,
 19.166186760838176,
 85.0986822588886]

# Assignment

In [ ]:
put the numbers above into ranges 0-10, 11-20,21-30,....100
72 should give "71-80"
31 should give "31-40"